### ISSUE TITLE
Getting a Cannot Find Module 'react/lib/merge' from ... error

### ISSUE THREAD

**Issue by dwoodlock** [joakimbeng/react-swiper#8]
I'm trying to incorporate your library into my React project.  I installed it through NPM using your recommended command:
npm install --save react react-swiper.
It installs without error.  
When I do my build via browserify, I'm getting this error: Getting a Cannot Find Module 'react/lib/merge' from c:\users\212026075\dropbox\textdon\node_modules\react-swiper
I'm using react v0.14.0.  I can see that react was not put into a subdirectory of react-swiper (don't know if that was supposed to happen).  And when I look at my react folder under node_modules it doesn't have a merge file under lib. 

Please advise.

**Comment by joakimbeng** [comment]
Fixed in `v0.1.5`
