### ISSUE TITLE
Source doesn't match delivered code

### ISSUE THREAD

**Issue by dwoodlock** [joakimbeng/react-swiper#9]
Hi there,
I had trouble trouble shooting using this module with React 0.13.3 because your source doesn't match the compiled code you deliver.  The source (jsx) using require('object-assign') which is good.  Maybe your package.json needs to indicate that - I didn't check.  However the transpiled code (js) uses require('react/lib/merge') which doesn't exist in .0.13.3.  If you update this repository with your currently transpiled code it should be fixed.  I would do it but don't know how to do a pull request.  Thanks.  
Don

**Comment by joakimbeng** [comment]
I see, I had forgot to publish the latest version to npm... A new `v0.1.5` is published now.
